/**
 * ============================================================================
 * REGIONAL ADMIN LOGIN MODAL (DISTRICT CREDENTIAL GATEWAY)
 * ============================================================================
 * 
 * Purpose:
 * Authenticates Regional Administrators using credentials created exclusively
 * by the Super Admin. Upon successful login, scopes all relief data access
 * strictly to that specific administrator's assigned Kerala district.
 */

import React, { useState } from 'react';
import { RegionalAdminAccount } from '../types';
import { authenticateRegionalAdmin, getStoredRegionalAdmins } from '../services/regionalAdminService';

interface RegionalAdminLoginModalProps {
  isOpen: boolean;
  onClose: () => void;
  onLoginSuccess: (admin: RegionalAdminAccount) => void;
  onShowToast: (title: string, message: string, type?: 'success' | 'warning' | 'info' | 'error') => void;
}

export const RegionalAdminLoginModal: React.FC<RegionalAdminLoginModalProps> = ({
  isOpen,
  onClose,
  onLoginSuccess,
  onShowToast
}) => {
  const [identifier, setIdentifier] = useState('');
  const [accessKey, setAccessKey] = useState('');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const [showPassword, setShowPassword] = useState(false);

  if (!isOpen) return null;

  const storedAdmins = getStoredRegionalAdmins().filter(a => a.status === 'Active');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg(null);

    const result = authenticateRegionalAdmin(identifier, accessKey);
    if (!result.success || !result.admin) {
      setErrorMsg(result.error || 'Authentication failed.');
      onShowToast('Login Failed', result.error || 'Invalid credentials.', 'error');
      return;
    }

    onShowToast(
      'Regional Admin Verified',
      `Welcome, ${result.admin.name}! Scoped to ${result.admin.districtName}.`,
      'success'
    );
    onLoginSuccess(result.admin);
    onClose();
  };

  const handleQuickFill = (admin: RegionalAdminAccount) => {
    // Fill with official Officer Credential ID and Password generated by Super Admin
    setIdentifier(admin.officerCredentialId || admin.sdmaOfficerId || admin.email);
    setAccessKey(admin.password || admin.accessKey || '');
    setErrorMsg(null);
  };

  return (
    <div className="modal-backdrop">
      <div 
        className="card modal-surface" 
        style={{ 
          maxWidth: '520px', 
          width: '95%',
          borderTop: '4px solid var(--color-secondary)',
          position: 'relative'
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 'var(--space-md)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div style={{
              width: '40px',
              height: '40px',
              borderRadius: 'var(--radius-sm)',
              backgroundColor: '#eff6ff',
              border: '1px solid #bfdbfe',
              color: 'var(--color-secondary)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center'
            }}>
              <span className="material-symbols-outlined" style={{ fontSize: '22px' }}>badge</span>
            </div>
            <div>
              <span className="badge badge-rls">Kerala District Relief Gateway</span>
              <h2 style={{ fontSize: '1.25rem', color: 'var(--color-secondary)', margin: '2px 0 0 0' }}>
                Regional Admin District Login
              </h2>
            </div>
          </div>

          <button
            type="button"
            className="btn btn-ghost btn-sm"
            onClick={onClose}
            style={{ padding: '4px', minHeight: 'auto' }}
          >
            <span className="material-symbols-outlined">close</span>
          </button>
        </div>

        <div style={{
          backgroundColor: '#eff6ff',
          border: '1px solid #bfdbfe',
          borderRadius: 'var(--radius-sm)',
          padding: '10px 12px',
          marginBottom: 'var(--space-md)',
          fontSize: '12px',
          color: '#1e3a8a',
          lineHeight: 1.5,
          display: 'flex',
          alignItems: 'flex-start',
          gap: '8px'
        }}>
          <span className="material-symbols-outlined" style={{ fontSize: '18px', color: 'var(--color-primary)', marginTop: '1px' }}>
            lock
          </span>
          <div>
            Please login using the <strong>Officer Credential ID</strong> and <strong>Password</strong> generated by the <strong>Super Administrator</strong> when provisioning your district account.
          </div>
        </div>

        {/* Error Alert */}
        {errorMsg && (
          <div style={{
            padding: '10px 12px',
            backgroundColor: '#fef2f2',
            border: '1px solid #fecaca',
            borderRadius: 'var(--radius-sm)',
            fontSize: '12px',
            color: '#b91c1c',
            marginBottom: 'var(--space-md)',
            display: 'flex',
            alignItems: 'center',
            gap: '8px'
          }}>
            <span className="material-symbols-outlined" style={{ fontSize: '18px' }}>error</span>
            <span>{errorMsg}</span>
          </div>
        )}

        {/* Login Form */}
        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-md)' }}>
          {/* Field 1: Officer Credential ID */}
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '4px' }}>
              <label style={{ fontSize: '12px', fontWeight: 700, color: 'var(--color-on-surface)' }}>
                Officer Credential ID *
              </label>
              <span className="badge" style={{ fontSize: '10px', backgroundColor: 'var(--color-surface-container)' }}>
                Generated by Super Admin
              </span>
            </div>
            <div style={{ position: 'relative' }}>
              <input
                type="text"
                className="input-field font-mono"
                placeholder="e.g. OFF-KL-WYD-401 or SDMA-KL-WYD-401"
                value={identifier}
                onChange={(e) => setIdentifier(e.target.value)}
                required
                autoFocus
                style={{ fontWeight: 600, paddingLeft: '36px' }}
              />
              <span className="material-symbols-outlined" style={{
                position: 'absolute',
                left: '10px',
                top: '50%',
                transform: 'translateY(-50%)',
                fontSize: '18px',
                color: 'var(--color-on-surface-variant)',
                pointerEvents: 'none'
              }}>
                badge
              </span>
            </div>
            <div style={{ fontSize: '11px', color: 'var(--color-on-surface-variant)', marginTop: '3px' }}>
              Unique district officer ID created by statewide administration (also accepts official registered email).
            </div>
          </div>

          {/* Field 2: Password */}
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '4px' }}>
              <label style={{ fontSize: '12px', fontWeight: 700, color: 'var(--color-on-surface)' }}>
                Password *
              </label>
              <button
                type="button"
                className="btn btn-ghost btn-sm"
                onClick={() => setShowPassword(!showPassword)}
                style={{ fontSize: '11px', padding: '2px 6px', minHeight: 'auto' }}
              >
                {showPassword ? 'Hide' : 'Show'} Password
              </button>
            </div>
            <div style={{ position: 'relative' }}>
              <input
                type={showPassword ? 'text' : 'password'}
                className="input-field font-mono"
                placeholder="Enter password generated by Super Admin"
                value={accessKey}
                onChange={(e) => setAccessKey(e.target.value)}
                required
                style={{ fontWeight: 600, paddingLeft: '36px' }}
              />
              <span className="material-symbols-outlined" style={{
                position: 'absolute',
                left: '10px',
                top: '50%',
                transform: 'translateY(-50%)',
                fontSize: '18px',
                color: 'var(--color-on-surface-variant)',
                pointerEvents: 'none'
              }}>
                password
              </span>
            </div>
            <div style={{ fontSize: '11px', color: 'var(--color-on-surface-variant)', marginTop: '3px' }}>
              District access password generated by Super Admin (can be updated later in your dashboard).
            </div>
          </div>

          {/* Quick Demo Helper */}
          {storedAdmins.length > 0 && (
            <div style={{
              backgroundColor: 'var(--color-surface-low)',
              borderRadius: 'var(--radius-sm)',
              padding: '10px 12px',
              border: '1px solid var(--color-outline-variant)'
            }}>
              <div style={{ fontSize: '11px', fontWeight: 700, color: 'var(--color-on-surface-variant)', marginBottom: '6px', display: 'flex', alignItems: 'center', gap: '4px' }}>
                <span className="material-symbols-outlined" style={{ fontSize: '14px' }}>bolt</span>
                <span>Quick-Select Active Kerala District Credentials (Demo):</span>
              </div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px' }}>
                {storedAdmins.map(adm => {
                  const offId = adm.officerCredentialId || adm.sdmaOfficerId;
                  const pass = adm.password || adm.accessKey || '';
                  return (
                    <button
                      key={adm.id}
                      type="button"
                      className="btn btn-ghost btn-sm"
                      onClick={() => handleQuickFill(adm)}
                      style={{
                        fontSize: '11px',
                        padding: '4px 8px',
                        backgroundColor: 'white',
                        border: '1px solid var(--color-outline-variant)',
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'flex-start',
                        textAlign: 'left',
                        gap: '1px'
                      }}
                      title={`Click to fill: Officer ID: ${offId} | Password: ${pass}`}
                    >
                      <div style={{ fontWeight: 700, color: 'var(--color-primary)' }}>
                        {adm.districtId.split('-')[1]}: {adm.name.split(' ')[0]}
                      </div>
                      <div className="font-mono" style={{ fontSize: '10px', color: 'var(--color-on-surface-variant)' }}>
                        ID: {offId}
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {/* Action Buttons */}
          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '8px', marginTop: 'var(--space-xs)' }}>
            <button
              type="button"
              className="btn btn-ghost"
              onClick={onClose}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="btn btn-secondary"
              style={{ padding: '8px 20px', fontWeight: 700 }}
            >
              <span className="material-symbols-outlined" style={{ fontSize: '16px' }}>login</span>
              <span>Verify &amp; Access District</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
